apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: contextpilot-api
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      serviceAccountName: contextpilot-sa
      containers:
      - image: gcr.io/PROJECT_ID/contextpilot-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: REWARDS_MODE
          value: "blockchain"  # or "firestore" for dev
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: gcp-project-id
              key: latest
        - name: GOOGLE_BLOCKCHAIN_NODE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: gcne-mumbai-endpoint
              key: latest
        - name: POLYGON_RPC_URL
          valueFrom:
            secretKeyRef:
              name: polygon-rpc-url
              key: latest
        - name: CPT_CONTRACT_ADDRESS
          valueFrom:
            secretKeyRef:
              name: cpt-contract-address
              key: latest
        - name: MINTER_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: minter-private-key
              key: latest
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: latest
        resources:
          limits:
            cpu: '2'
            memory: '1Gi'

