apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: cpt-batch-minter
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    spec:
      template:
        spec:
          serviceAccountName: contextpilot-minter-sa
          containers:
          - image: gcr.io/PROJECT_ID/cpt-batch-minter:latest
            command: ["python", "-m", "app.workers.batch_minter"]
            env:
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: gcp-project-id
                  key: latest
            - name: GOOGLE_BLOCKCHAIN_NODE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: gcne-mumbai-endpoint
                  key: latest
            - name: POLYGON_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: polygon-rpc-url
                  key: latest
            - name: CPT_CONTRACT_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: cpt-contract-address
                  key: latest
            - name: MINTER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: minter-private-key
                  key: latest
            - name: MAX_GAS_GWEI
              value: "50"
            resources:
              limits:
                cpu: '1'
                memory: '512Mi'
            timeout: 600s

