# Cloud Build configuration for ContextPilot
# Builds and deploys API + Workers to Cloud Run

steps:
  # Build API container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/contextpilot-api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/contextpilot-api:latest'
      - '-f'
      - 'back-end/Dockerfile'
      - 'back-end/'
  
  # Build batch minter worker
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-minter'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cpt-batch-minter:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cpt-batch-minter:latest'
      - '-f'
      - 'back-end/Dockerfile.worker'
      - 'back-end/'
  
  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api'
    args: ['push', 'gcr.io/$PROJECT_ID/contextpilot-api:$SHORT_SHA']
    waitFor: ['build-api']
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-minter'
    args: ['push', 'gcr.io/$PROJECT_ID/cpt-batch-minter:$SHORT_SHA']
    waitFor: ['build-minter']
  
  # Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'contextpilot-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/contextpilot-api:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
    waitFor: ['push-api']
  
  # Deploy batch minter job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-minter'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'cpt-batch-minter'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cpt-batch-minter:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--execute-now'  # Run immediately after deploy
    waitFor: ['push-minter']

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/contextpilot-api:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/contextpilot-api:latest'
  - 'gcr.io/$PROJECT_ID/cpt-batch-minter:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/cpt-batch-minter:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'

