# Google Cloud Build configuration for ContextPilot Backend

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/contextpilot-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/contextpilot-backend:latest'
      - '.'
    dir: 'back-end'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/contextpilot-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/contextpilot-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'contextpilot-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/contextpilot-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'USE_PUBSUB=true,FIRESTORE_ENABLED=true,ENVIRONMENT=production'

images:
  - 'gcr.io/$PROJECT_ID/contextpilot-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/contextpilot-backend:latest'

timeout: '1200s'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

