[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Polygon Mumbai testnet
[rpc_endpoints]
mumbai = "https://rpc-mumbai.maticvigil.com"
polygon = "https://polygon-rpc.com"

# Etherscan verification
[etherscan]
mumbai = { key = "${POLYGONSCAN_API_KEY}" }

# Gas reporting
gas_reports = ["CPT"]

# Remappings for OpenZeppelin
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

