name: Create PR from Sandbox

on:
  push:
    branches: [dev-agent/*]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create PR from'
        required: true
        default: 'dev-agent/feature'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sandbox
        uses: actions/checkout@v4
        with:
          repository: fsegall/contextpilot-sandbox
          ref: ${{ github.ref_name }}
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Create PR to main repo
        uses: actions/github-script@v7
        with:
          script: |
            const branch = '${{ github.ref_name }}';
            const title = `🤖 Dev Agent: ${branch.replace('dev-agent/', '')}`;
            const body = `## Automated PR from Development Agent
            
            **Branch:** \`${branch}\`
            **Agent:** Development Agent (Sandbox Mode)
            **Generated:** ${new Date().toISOString()}
            
            ### Changes
            This PR contains automated changes generated by the Development Agent based on retrospective insights.
            
            ### Review Checklist
            - [ ] Code quality looks good
            - [ ] Tests pass
            - [ ] No breaking changes
            - [ ] Documentation updated if needed
            
            ---
            *This PR was automatically created by the ContextPilot Development Agent.*`;

            const { data: pr } = await github.rest.pulls.create({
              owner: 'fsegall',
              repo: 'gcloud_contextpilot',
              title: title,
              head: `fsegall:${branch}`,
              base: 'main',
              body: body,
              draft: false
            });

            console.log(`✅ Created PR #${pr.number}: ${pr.html_url}`);
            
            # Add labels
            await github.rest.issues.addLabels({
              owner: 'fsegall',
              repo: 'gcloud_contextpilot',
              issue_number: pr.number,
              labels: ['dev-agent', 'automated']
            });
