name: Sync Main to Sandbox

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Sync to sandbox
        run: |
          # Configure git
          git config --global user.name "ContextPilot Bot"
          git config --global user.email "bot@contextpilot.dev"
          
          # Verify we're on main branch
          git branch --show-current
          
          # Add sandbox as remote with personal token
          git remote add sandbox https://${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/fsegall/contextpilot-sandbox.git
          
          # Verify remote was added
          git remote -v
          
          # Configure git to use the personal token for this push
          git config --global url."https://${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          
          # Push to sandbox main branch with verbose output
          git push sandbox main:main --force --verbose
          
          echo "✅ Synced main to sandbox successfully"
