name: Sync Main to Sandbox

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      SANDBOX_REPO_URL: ${{ vars.SANDBOX_REPO_URL }}
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Sync to sandbox
        run: |
          # Configure git
          git config --global user.name "ContextPilot Bot"
          git config --global user.email "bot@contextpilot.dev"
          
          # Verify we're on main branch
          git branch --show-current
          
          # Resolve sandbox remote URL (from repo variable or fallback)
          REMOTE_URL="${SANDBOX_REPO_URL}"
          if [ -z "$REMOTE_URL" ]; then
            REMOTE_URL="https://github.com/fsegall/contextpilot-sandbox.git"
          fi
          # Add sandbox as remote with personal token
          AUTH_REMOTE_URL="${REMOTE_URL/https:\/\//https:\/\/${{ secrets.PERSONAL_GITHUB_TOKEN }}@}"
          git remote add sandbox "$AUTH_REMOTE_URL"
          
          # Verify remote was added
          git remote -v
          
          # Configure git to use the personal token for this push
          git config --global url."https://${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          
          # Push to sandbox main branch with verbose output
          git push sandbox main:main --force --verbose
          
          echo "✅ Synced main to sandbox successfully"
