name: Sync Main to Sandbox

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync to sandbox
        run: |
          # Configure git
          git config --global user.name "ContextPilot Bot"
          git config --global user.email "bot@contextpilot.dev"
          
          # Add sandbox as remote with personal token
          git remote add sandbox https://${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/fsegall/contextpilot-sandbox.git
          
          # Push to sandbox main branch
          git push sandbox main:main --force
          
          echo "✅ Synced main to sandbox successfully"
